title: BlueDot Documentation
description: BlueDot products documentation.
theme: just-the-docs

url: https://bluedot-arcade.github.io/docs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
