title: Docs
description: BlueDot products documentation.
theme: just-the-docs

url: https://docs.bluedotarcade.com

aux_links:
  Template Repository: https://github.com/bluedot-arcade/bluedot-docs
  Test Link: https://helloworld.com

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"

# Footer
footer_content: "Copyright &copy; 2022-2023 BlueDot Arcade. This site is powered by <a href=\"https://pages.github.com\">Github Pages.</a>"
