title: BlueDot Documentation
description: BlueDot products documentation.
theme: just-the-docs

url: https://docs.bluedotarcade.com

aux_links:
  Github repository: https://github.com/bluedot-arcade/bluedot-docs

# Color scheme
color_scheme: bluelight

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red


# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Logo and icon
logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"

# Footer
footer_content: "Copyright &copy; 2022-2023 BlueDot Arcade. This site is powered by <a href=\"https://pages.github.com\">Github Pages.</a>"
